import { tool } from "@opencode-ai/plugin"
import { readFileSync, writeFileSync, existsSync } from "fs"

// Cell-level notebook composition (issue #86). nb-note appends to the notebook's
// FIRST cell — the markdown "preamble" that must always sit at the top and hold
// the provenance line plus the composer's disclosures about what it
// reconstructed (figures regenerated by re-invoking a tool/library, code
// reproduced at a coarser level than it originally ran, results trusted from a
// summary because a step failed, inherited data). Index-independent: it always
// targets the preamble, which shifts as cells are added and as nb-finalize runs,
// so the composer never has to track its position.

function emptyNb(): any {
  return {
    cells: [],
    metadata: {
      kernelspec: { name: "python3", display_name: "Python 3" },
      language_info: { name: "python" },
    },
    nbformat: 4,
    nbformat_minor: 5,
  }
}

function loadNb(path: string): any {
  if (!existsSync(path)) return emptyNb()
  try {
    return JSON.parse(readFileSync(path, "utf-8"))
  } catch {
    return emptyNb()
  }
}

function saveNb(path: string, nb: any): void {
  writeFileSync(path, JSON.stringify(nb, null, 1) + "\n")
}

function escapeDollar(text: string, math?: boolean): string {
  return math ? text : text.replace(/\$/g, "\\$")
}

function srcText(source: any): string {
  return (typeof source === "string" ? source : (source ?? []).join(""))
}

export default tool({
  description:
    "Append a note to the notebook's FIRST cell — the markdown preamble at the very top. Use this to " +
    "DISCLOSE anything you reconstructed rather than took verbatim: figures regenerated by re-invoking a " +
    "tool or library (rather than the exact code that ran), code reproduced at a coarser level than it " +
    "originally ran, results trusted from a summary because a step failed, or inherited data. Creates the " +
    "preamble cell if the notebook has no leading markdown cell. '$' is escaped by default.",

  args: {
    notebook: tool.schema.string().describe("Path to the .ipynb file"),
    text: tool.schema.string().describe("The note (markdown) to append to the preamble cell"),
    math: tool.schema.boolean().optional()
      .describe("Keep '$' literal for MathJax (default false: '$' is escaped)"),
  },

  async execute({ notebook, text, math }) {
    const nb = loadNb(notebook)
    if (!nb.cells) nb.cells = []
    const note = escapeDollar(text, math)
    const first = nb.cells[0]
    if (first && first.cell_type === "markdown") {
      first.source = srcText(first.source).replace(/\s+$/, "") + "\n\n" + note
    } else {
      // no leading markdown cell — establish the preamble at the top
      nb.cells.unshift({ cell_type: "markdown", metadata: {}, source: note })
    }
    saveNb(notebook, nb)
    return `Appended a note to the preamble cell of ${notebook}`
  },
})
